# Generated by Django 5.2.5 on 2026-05-03 23:55

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre empresa')),
                ('razon_social', models.CharField(blank=True, max_length=200, null=True, verbose_name='Razón social (SII)')),
                ('rut', models.CharField(blank=True, help_text='Ej: 76.123.456-K', max_length=12, null=True, verbose_name='RUT empresa')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección comercial')),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('email_rrhh', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email RRHH (alertas)')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo empresa')),
                ('activa', models.BooleanField(default=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('tolerancia_atraso_min', models.PositiveIntegerField(default=10, help_text='Minutos de gracia antes de contar como atraso', verbose_name='Tolerancia atraso (minutos)')),
                ('jornada_semanal_horas', models.PositiveIntegerField(default=45, help_text='Máximo legal: 45 horas (Art. 22 CT)', verbose_name='Horas jornada semanal')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('descripcion', models.CharField(max_length=150)),
                ('es_irrenunciable', models.BooleanField(default=True, help_text='Navidad, 1 de mayo, Fiestas Patrias, etc.', verbose_name='Feriado irrenunciable')),
            ],
            options={
                'verbose_name': 'Feriado',
                'verbose_name_plural': 'Feriados',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='DiaAdministrativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo_jornada', models.CharField(choices=[('COMPLETO', 'Día completo'), ('MANANA', 'Media jornada mañana'), ('TARDE', 'Media jornada tarde')], default='COMPLETO', max_length=10)),
                ('motivo', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=15)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('comentario_rrhh', models.CharField(blank=True, max_length=300)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_administrativos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Día administrativo',
                'verbose_name_plural': 'Días administrativos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='LicenciaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
                ('tipo', models.CharField(choices=[('ENFERMEDAD', 'Enfermedad común'), ('ACCIDENTE', 'Accidente laboral (ACHS/Mutual)'), ('MATERNAL', 'Pre/post natal'), ('OTRO', 'Otro motivo')], default='ENFERMEDAD', max_length=20)),
                ('folio', models.CharField(blank=True, max_length=50, verbose_name='N° folio licencia')),
                ('documento', models.FileField(blank=True, null=True, upload_to='licencias/%Y/', verbose_name='Documento PDF')),
                ('observacion', models.TextField(blank=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licencias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Licencia médica',
                'verbose_name_plural': 'Licencias médicas',
                'ordering': ['-inicio'],
            },
        ),
        migrations.CreateModel(
            name='Marcacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('INICIO_COLACION', 'Inicio colación'), ('FIN_COLACION', 'Fin colación'), ('SALIDA', 'Salida')], max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora exacta (NTP)')),
                ('estado', models.CharField(choices=[('VIGENTE', 'Vigente'), ('RECTIFICADA', 'Rectificada (histórico)'), ('ANULADA', 'Anulada')], default='VIGENTE', max_length=20)),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('direccion', models.CharField(blank=True, max_length=300, verbose_name='Dirección geocodificada')),
                ('precision_gps', models.FloatField(blank=True, null=True, verbose_name='Precisión GPS (metros)')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='marcas/%Y/%m/', verbose_name='Foto de verificación')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('es_manual', models.BooleanField(default=False, verbose_name='Marca ingresada manualmente')),
                ('observacion', models.TextField(blank=True)),
                ('animo', models.CharField(blank=True, choices=[('FELIZ', 'Motivado'), ('NEUTRAL', 'Normal'), ('MOLESTO', 'Bajo / Cansado')], max_length=10, null=True)),
                ('comentario_animo', models.TextField(blank=True, null=True)),
                ('alerta_olvido_enviada', models.BooleanField(default=False)),
                ('hash_previo', models.CharField(blank=True, max_length=64, verbose_name='Hash registro anterior')),
                ('hash_actual', models.CharField(blank=True, editable=False, max_length=64, verbose_name='Hash de este registro')),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marcaciones', to='asistencia.empresa')),
                ('marca_reemplazada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reemplazos', to='asistencia.marcacion')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Marcación',
                'verbose_name_plural': 'Marcaciones',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(blank=True, max_length=12, null=True, verbose_name='RUT trabajador')),
                ('cargo', models.CharField(blank=True, max_length=100, verbose_name='Cargo / Puesto')),
                ('rol', models.CharField(choices=[('TRABAJADOR', 'Trabajador'), ('EMPLEADOR', 'Empleador / RRHH'), ('FISCALIZADOR', 'Fiscalizador DT'), ('SUPERADMIN', 'Superadministrador')], default='TRABAJADOR', max_length=20)),
                ('hora_entrada', models.TimeField(default=datetime.time(9, 0), verbose_name='Hora entrada oficial')),
                ('jornada_diaria', models.PositiveIntegerField(default=9, verbose_name='Horas por jornada diaria')),
                ('trabaja_lunes', models.BooleanField(default=True, verbose_name='Lunes')),
                ('trabaja_martes', models.BooleanField(default=True, verbose_name='Martes')),
                ('trabaja_miercoles', models.BooleanField(default=True, verbose_name='Miércoles')),
                ('trabaja_jueves', models.BooleanField(default=True, verbose_name='Jueves')),
                ('trabaja_viernes', models.BooleanField(default=True, verbose_name='Viernes')),
                ('trabaja_sabado', models.BooleanField(default=False, verbose_name='Sábado')),
                ('trabaja_domingo', models.BooleanField(default=False, verbose_name='Domingo')),
                ('cambiar_pass', models.BooleanField(default=True, verbose_name='Debe cambiar contraseña en primer ingreso')),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajadores', to='asistencia.empresa')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.CreateModel(
            name='SolicitudMarca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_solicitud', models.CharField(choices=[('NUEVA', 'Nueva marca (olvido / falla técnica)'), ('RECTIFICACION', 'Corrección de hora existente')], max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de aprobación'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20)),
                ('fecha_hora_propuesta', models.DateTimeField()),
                ('tipo_marca_propuesta', models.CharField(max_length=20)),
                ('motivo', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('marca_original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asistencia.marcacion')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_creadas', to=settings.AUTH_USER_MODEL)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_marca', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de marca',
                'verbose_name_plural': 'Solicitudes de marca',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre del turno')),
                ('hora_inicio', models.TimeField(verbose_name='Hora inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora fin')),
                ('color', models.CharField(default='#1a6644', help_text='Color HEX para el calendario', max_length=7)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='asistencia.empresa')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de turno')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos_asignados', to=settings.AUTH_USER_MODEL)),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.turno')),
            ],
            options={
                'verbose_name': 'Asignación de turno',
                'verbose_name_plural': 'Asignaciones de turno',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Vacacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField(verbose_name='Fecha inicio')),
                ('fin', models.DateField(verbose_name='Fecha fin')),
                ('dias_habiles', models.PositiveIntegerField(default=0, help_text='Se calcula automáticamente excluyendo feriados', verbose_name='Días hábiles descontados')),
                ('comentario', models.CharField(blank=True, max_length=300)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de aprobación'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=15)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('comentario_rrhh', models.CharField(blank=True, max_length=300)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacaciones_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vacación',
                'verbose_name_plural': 'Vacaciones',
                'ordering': ['-inicio'],
            },
        ),
        migrations.CreateModel(
            name='LogAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('AUSENCIA', 'Ausencia injustificada'), ('EXCESO_HORAS', 'Exceso de jornada (+2h)'), ('SIN_SALIDA', 'Sin marca de salida')], max_length=20)),
                ('fecha', models.DateField()),
                ('enviado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asistencia.empresa')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de alerta',
                'verbose_name_plural': 'Logs de alertas',
                'ordering': ['-enviado_en'],
                'unique_together': {('trabajador', 'tipo', 'fecha')},
            },
        ),
        migrations.AddIndex(
            model_name='marcacion',
            index=models.Index(fields=['trabajador', 'timestamp'], name='asistencia__trabaja_85fd08_idx'),
        ),
        migrations.AddIndex(
            model_name='marcacion',
            index=models.Index(fields=['empresa', 'timestamp'], name='asistencia__empresa_f12290_idx'),
        ),
        migrations.AddIndex(
            model_name='marcacion',
            index=models.Index(fields=['tipo', 'timestamp'], name='asistencia__tipo_f49886_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='turno',
            unique_together={('empresa', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='asignacionturno',
            unique_together={('trabajador', 'fecha')},
        ),
    ]
