# Generated by Django 5.2.5 on 2026-05-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0003_perfil_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenciamedica',
            name='comentario_rrhh',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='licenciamedica',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de revisión'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=15),
        ),
    ]
