# Generated by Django 5.1.15 on 2026-05-08 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0004_licenciamedica_comentario_rrhh_licenciamedica_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='marcacion',
            name='foto_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL foto Cloudinary'),
        ),
    ]
